library(easypackages)
library(xts)
library(lattice)
library(ggplot2)
pdiaria <- read.csv(file.choose(),header=TRUE, check.names = F, stringsAsFactors = F)
str(pdiaria)
idx <- as.Date(pdiaria[,1])
data.matrix <- pdiaria[,-1]
data.xts <- xts(data.matrix, order.by = idx )
str(data.xts)
plot(data.xts)
plot(data.matrix[,1], type="l")
plot(data.xts[,3])
data.monthly <- apply.monthly(data.xts[,3], FUN = sum)
plot(data.monthly)
data.monthly <- apply.monthly(data.xts, FUN=apply, MARGIN = 2, sum)
xyplot(data.monthly, ylim = c(0,600))
data.anual <- apply.yearly(data.xts[,3], FUN = sum) 
barplot(data.anual)
data.anual <- apply.yearly(data.monthly, FUN=apply, 2, sum) 
xyplot(data.anual)
boxplot(coredata(data.monthly))
boxplot(matrix(coredata(data.monthly[,3]), nrow=nrow(data.monthly)/12, ncol=12, byrow=T), col="gray", main=c(paste(names(data.monthly[,3])), "Prec mensual [mm]")) 
