rain<-c(20, 21.2, 49, 10.5, 15.1, 19, 31, 20.2)
soi<-c(0.2, 0.4, 1.5, -0.1, 0.15, 0.3, 0.9, 1.1)
hist(rain, main="Precipitacion anual", xlab="P (mm/año)", freq=F) 
curve(dnorm(x, mean(rain, na.rm = T), sd(rain, na.rm = T)), add = TRUE, col="red") 
split.screen(c(1,2)) 
screen(2) 
close.screen(all=TRUE) 
cov(rain,soi) 
cor(rain,soi)
lm(soi~rain)
plot(rain,soi,main="ENSO-rainfall relationship",xlab="rainfall", ylab="SOI index")
abline(lm(soi~rain))